server:
  port: 8001



spring:
  thymeleaf:
    mode: LEGACYHTML5
  activemq:
    broker-url: failover:(tcp://192.168.249.134:61616,tcp://192.168.249.135:61616,tcp://192.168.249.136:61616)
    user: admin
    password: admin
    pool:
      enabled: true
  jms:
    pub-sub-domain: true



app:
  message:
    #消息队列地址
    activeMQAddr: failover:(tcp://192.168.249.134:61616,tcp://192.168.249.135:61616,tcp://192.168.249.136:61616)
    #mq连接池最大连接数
    mqMaxConnections: 10
    #mq连接池最小连接数
    mqminConnections: 3
    #mq后台对象清理时，休眠时间超过了3000毫秒的对象为过期
    expirationCheckMillis: 3000
    #消息重发策略   消息重发间隔
    redeliveryDelay: 6000
    #消息重发最大次数
    maximumRedeliveries: 2
    # Spring Caching连接工厂  Session缓存数量
    sessionCacheSize: 100
    # 以下属性配置队列名称
    myqueue: boot-queue
    myqueue2: boot-queue2